name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Create Release and Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="v1.0.${{ github.run_number }}"
          RELEASE_NAME="iOS Release v1.0.${{ github.run_number }}"
          
          # Create release
          gh release create "$TAG_NAME" \
            --title "$RELEASE_NAME" \
            --notes "This is an iOS release build

          Built from commit: ${{ github.sha }}

          ## Changes
          - Initial iOS release build" \
            --draft=false \
            --prerelease=false || true
          
          # Upload asset
          gh release upload "$TAG_NAME" build/ios/iphoneos/FlutterIpaExport.ipa --clobber
